routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AppController@index')->name('/');
Route::get('/about', 'AppController@about')->name('about');
Route::get('/news-update', 'AppController@news')->name('news');
Route::get('/contact', 'AppController@inquiries')->name('inquiries');
Route::get('/projects/{page:slug}', 'AppController@detailProject')->name('project');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::prefix('admin')->namespace('Admin')->middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/images', 'ImageController', ['except' => ['create', 'show', 'edit', 'update']]);
    Route::resource('/pages', 'PageController');
    Route::put('/pages/{page}/pageDescriptions/{pageDescription}', 'PageDescriptionController@update')->name('pageDescriptions.update');
    Route::post('/slides/update-slide', 'SlideController@updateSlide')->name('slides.update_slide');

    Route::put('/slides/update', 'SlideController@update')->name('slides.update');

    Route::resource('/pages/{page}/projectDetails', 'ProjectDetailController', ['except' => 'index', 'show', 'edit']);
    Route::get('/pages/{page}/projectDetails/{projectDetail}/edit-image', 'ProjectDetailController@editImage')->name('projectDetails.edit_image');
    Route::put('/pages/{page}/projectDetails/{projectDetail}', 'ProjectDetailController@updateImage')->name('projectDetails.update_image');

    Route::get('/pages/main/about', 'PageController@about')->name('pages.about');
    Route::get('/pages/main/{page}/choose-image', 'PageController@chooseImage')->name('pages.choose_image');
    Route::post('/pages/main/{page}/choose-image', 'PageController@updateImage')->name('pages.update_image');
    Route::put('/pages/main/{page}/order', 'PageController@updateImageOrder')->name('pages.update_image_order');
    Route::delete('/pages/main/about', 'PageController@deleteImage')->name('pages.delete_image');
    Route::get('/pages/main/news-update', 'PageController@news')->name('pages.news');
    Route::get('/pages/main/inquiries', 'PageController@inquiries')->name('pages.inquiries');
    Route::get('/pages/main/media', 'PageController@media')->name('pages.media');
    
    Route::get('/settings/{setting}/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('/settings/{setting}', 'SettingController@update')->name('settings.update');
});

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model {
    protected $guarded = [];

    public function pages() {
        return $this->morphedByMany(Page::class, 'imageable');
    }

    public function slides() {
        return $this->morphedByMany(Slide::class, 'imageable');
    }

    public function projectDetails() {
        return $this->hasMany(ProjectDetail::class);
    }

    protected static function boot() {
        parent::boot();

        static::deleting(function ($image) {
            $image->pages()->detach();
            $image->slides()->detach();
            $image->projectDetails()->delete();
        });
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image as InvImage;
use Illuminate\Support\Str;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $thumbs = Image::where('src', 'LIKE', '%_thumb%')->get();
        $images = Image::where('src', 'NOT LIKE', '%_thumb%')->get();

        return view('pages.admin.image.index', compact('images', 'thumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ini_set('memory_limit', '512M');

        $request->validate(['image' => 'required|image|max:2048']);

        $basename = Str::random();
        $originalPath = 'uploads/images/' . $basename . '.' . $request->image->getClientOriginalExtension();
        $thumbnailPath =  'uploads/images/' . $basename . '_thumb.' . $request->image->getClientOriginalExtension();

        $thumbnail = InvImage::make($request->image);

        Image::create(['src' => $thumbnailPath]);

        if ($request->image->getClientOriginalExtension() == 'gif') {
            copy($request->image->getRealPath(), storage_path('app/public/' . $thumbnailPath));
        } else {
            if ($thumbnail->filesize() >= 1024000) {
                $thumbnail->resize(null, 800, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                })->save(storage_path('app/public/' . $thumbnailPath));
            } else {
                $thumbnail->resize(null, 1000, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                })->save(storage_path('app/public/' . $thumbnailPath));
            }
        }

        Image::create(['src' => $originalPath]);

        $request->file('image')->move(storage_path('app/public/uploads/images'), $originalPath);

        session()->flash('message', 'Image successfully uploaded!');
        session()->flash('alert-class', 'alert-success');

        return redirect(route('images.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function destroy(Image $image)
    {
        $thumbnailImgFile = explode('.', $image->src)[0] . '_thumb.' . explode('.', $image->src)[1];
        $thumbnailImg = Image::where('src', $thumbnailImgFile)->first();

        Storage::delete('/storage/' . $image->src);
        Storage::delete('/storage/' . $thumbnailImgFile);

        $image->delete();
        $thumbnailImg->delete();

        session()->flash('message', 'Image successfully deleted!');
        session()->flash('alert-class', 'alert-danger');

        return redirect(route('images.index'));
    }
}

resources/views/pages/admin/image/index.blade.php
@extends('layouts.app', ['title' => 'Image Assets'])

@section('content')
@include('layouts.headers.cards')

<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0 d-flex justify-content-between align-items-center">
                    <h3 class="mb-0">Image Assets</h3>

                    <div class="btn btn-primary">
                        <label for="upload-btn" class="m-0">
                            Upload Image
                        </label>

                        <form action="{{ route('images.store') }}" method="post" class="d-none"
                            enctype="multipart/form-data">
                            @csrf
                            <input type="file" name="image" onchange="form.submit()" id="upload-btn">
                        </form>
                    </div>
                </div>
                <hr class="my-1">
                <div class="card-body">
                    @if (request()->session()->has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                        <span class="alert-inner--text">
                            {{ session()->get('message') }}
                        </span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                    @error('image')
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <span class="alert-inner--icon"><i class="ni ni-fat-remove"></i></span>
                        <span class="alert-inner--text">
                            {{ $message }}
                        </span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @enderror
                    <div class="d-flex flex-wrap justify-content-around">
                        @forelse ($thumbs as $thumb)
                        <div class="w-25 mx-2 mb-4 d-flex">
                            <img loading="lazy" src="{{ asset('storage/' . $thumb->src) }}"
                                class="w-100 h-150px rounded">
                            <span class="text-right">
                                <div class="dropdown">
                                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                        <form id="delete-image-{{$thumb->id}}"
                                            action="{{ route('images.destroy', $images[$loop->index]) }}" method="POST"
                                            style="display: none;">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <a href="{{ route('images.destroy', $thumb) }}" class="dropdown-item" onclick="event.preventDefault();
                                        document.getElementById('delete-image-{{$thumb->id}}').submit();">
                                            Delete
                                        </a>
                                    </div>
                                </div>
                            </span>
                        </div>
                        @empty
                        <div class="text-center">
                            <span class="font-weight-bold text-warning">Image data is empty!</span>
                        </div>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('layouts.footers.auth')
</div>
@endsection