routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AppController@index')->name('/');
Route::get('/about', 'AppController@about')->name('about');
Route::get('/news-update', 'AppController@news')->name('news');
Route::get('/contact', 'AppController@inquiries')->name('inquiries');
Route::get('/projects/{page:slug}', 'AppController@detailProject')->name('project');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::prefix('admin')->namespace('Admin')->middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/images', 'ImageController', ['except' => ['create', 'show', 'edit', 'update']]);
    Route::resource('/pages', 'PageController');
    Route::put('/pages/{page}/pageDescriptions/{pageDescription}', 'PageDescriptionController@update')->name('pageDescriptions.update');
    Route::post('/slides/update-slide', 'SlideController@updateSlide')->name('slides.update_slide');

    Route::put('/slides/update', 'SlideController@update')->name('slides.update');

    Route::resource('/pages/{page}/projectDetails', 'ProjectDetailController', ['except' => 'index', 'show', 'edit']);
    Route::get('/pages/{page}/projectDetails/{projectDetail}/edit-image', 'ProjectDetailController@editImage')->name('projectDetails.edit_image');
    Route::put('/pages/{page}/projectDetails/{projectDetail}', 'ProjectDetailController@updateImage')->name('projectDetails.update_image');

    Route::get('/pages/main/about', 'PageController@about')->name('pages.about');
    Route::get('/pages/main/{page}/choose-image', 'PageController@chooseImage')->name('pages.choose_image');
    Route::post('/pages/main/{page}/choose-image', 'PageController@updateImage')->name('pages.update_image');
    Route::put('/pages/main/{page}/order', 'PageController@updateImageOrder')->name('pages.update_image_order');
    Route::delete('/pages/main/about', 'PageController@deleteImage')->name('pages.delete_image');
    Route::get('/pages/main/news-update', 'PageController@news')->name('pages.news');
    Route::get('/pages/main/inquiries', 'PageController@inquiries')->name('pages.inquiries');
    Route::get('/pages/main/media', 'PageController@media')->name('pages.media');
    
    Route::get('/settings/{setting}/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('/settings/{setting}', 'SettingController@update')->name('settings.update');
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
@include('layouts.navbars.navs.auth', ['title' => $title])
@endauth

@guest()
@include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
            aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand" href="{{ route('home') }}">
            {{ $setting->site_name }} Panel
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                            <img alt="Image placeholder"
                                src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    {{-- <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My Profile</span>
                    </a> --}}
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        {{ $setting->site_name }} Panel
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                            data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                            aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended"
                        placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Divider -->
            <hr class="m-0">
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('admin/home') ? 'active' : '' }}" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('admin/images') ? 'active' : '' }}"
                        href="{{ route('images.index') }}">
                        <i class="ni ni-image text-info"></i> Image Assets
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#navbar-1" data-toggle="collapse" role="button" aria-expanded="true"
                        aria-controls="navbar-1">
                        <i class="ni ni-ungroup text-red"></i>
                        Main Pages
                    </a>

                    <div class="collapse show" id="navbar-1">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages') ? 'active' : '' }}"
                                    href="{{ route('pages.index') }}">
                                    Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages/main/about') ? 'active' : '' }}"
                                    href="{{ route('pages.about') }}">
                                    About
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages/main/inquiries') ? 'active' : '' }}"
                                    href="{{ route('pages.inquiries') }}">
                                    Inquiries
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages/main/news-update') ? 'active' : '' }}"
                                    href="{{ route('pages.news') }}">
                                    News
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages/main/media') ? 'active' : '' }}"
                                    href="{{ route('pages.media') }}">
                                    Media
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="#navbar-2" data-toggle="collapse" role="button" aria-expanded="true"
                        aria-controls="navbar-2">
                        <i class="ni ni-ungroup text-orange"></i>
                        Project Pages
                    </a>

                    <div class="collapse show" id="navbar-2">
                        <ul class="nav nav-sm flex-column">
                            @for ($i = 1; $i <= 40; $i++) <li class="nav-item">
                                <a class="nav-link {{ request()->is('admin/pages/'.$i) ? 'active' : '' }}"
                                    href="{{ route('pages.show', $i) }}">
                                    Project {{ $i }}
                                </a>
                </li>
                @endfor
        </div>
        </li>
        </ul>
    </div>
    </div>
</nav>